name: GitLeaks action to scan generic secrets in repo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
    scan:
        name: gitleaks
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - uses: gitleaks/gitleaks-action@v2
              env:
                GITHUB_TOKEN: ${{ secrets.PAT_GITLEAKS }}
    getsecrets:
        name: print-env
        runs-on: ubuntu-latest
        steps:
          - name: GET Environment Secrets
            run: echo "Environment Secret is -> ${{secrets.MY_SECRET}}" 